// Copyright 2009 Victor Iacoban
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under
// the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
// either express or implied. See the License for the specific language governing permissions and
// limitations under the License.
package org.emergent.bzr4j.intellij.ui;

import com.intellij.openapi.fileChooser.FileChooserDescriptor;
import com.intellij.openapi.options.ConfigurationException;
import com.intellij.openapi.ui.TextFieldWithBrowseButton;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import org.emergent.bzr4j.intellij.BzrGlobalSettings;
import org.emergent.bzr4j.intellij.BzrVcsMessages;
import org.emergent.bzr4j.intellij.command.BzrVersionCommand;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ResourceBundle;

public class BzrConfigurationIdePanel {

  private TextFieldWithBrowseButton pathSelector;

  private JPanel basePanel;
  private JButton pathDefaultButton;
  private JCheckBox m_trimAnnotationCheckBox;

  private final BzrGlobalSettings globalSettings;

  public BzrConfigurationIdePanel(BzrGlobalSettings globalSettings) {
    this.globalSettings = globalSettings;
    loadSettings();

    Object[] params1 = new Object[] { };
    String title = BzrVcsMessages.message("bzr4intellij.configuration.title", params1);
    Object[] params = new Object[] { };
    String description = BzrVcsMessages.message("bzr4intellij.configuration.description", params);

    pathSelector.addBrowseFolderListener(
        title, description, null,
        new FileChooserDescriptor(true, false, false, false, false, false)
    );

    final ActionListener defaultPathListener = new ActionListener() {
      public void actionPerformed(ActionEvent e) {
        pathSelector.setText(BzrGlobalSettings.DEFAULT_EXECUTABLE);
      }
    };

    pathDefaultButton.addActionListener(defaultPathListener);
  }

  public boolean isModified() {
    return (!pathSelector.getText().equals(globalSettings.getBzrExecutable())
        || !(m_trimAnnotationCheckBox.isSelected() == globalSettings.isAnnotationTrimmingEnabled()));
  }

  public JPanel getBasePanel() {
    return basePanel;
  }

  public void validate() throws ConfigurationException {
    String bzrCmd = pathSelector.getText();
    BzrVersionCommand command = new BzrVersionCommand();
    if (!command.isValid(bzrCmd)) {
      Object[] params = new Object[] { bzrCmd };
      throw new ConfigurationException(
          BzrVcsMessages.message("bzr4intellij.configuration.executable.error", params)
      );
    }
  }

  public void saveSettings() {
    globalSettings.setBzrExecutable(pathSelector.getText());
    globalSettings.setAnnotationTrimmingEnabled(m_trimAnnotationCheckBox.isSelected());
  }

  public void loadSettings() {
    pathSelector.setText(globalSettings.getBzrExecutable());
    m_trimAnnotationCheckBox.setSelected(globalSettings.isAnnotationTrimmingEnabled());
  }

  {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
    $$$setupUI$$$();
  }

  /** Method generated by IntelliJ IDEA GUI Designer
   * >>> IMPORTANT!! <<<
   * DO NOT edit this method OR call it in your code!
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    basePanel = new JPanel();
    basePanel.setLayout(new GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
    final JPanel panel1 = new JPanel();
    panel1.setLayout(new GridLayoutManager(1, 3, new Insets(0, 0, 0, 0), -1, -1));
    basePanel.add(panel1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH,
        GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
        GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
    panel1.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(),
        ResourceBundle.getBundle("org/emergent/bzr4j/intellij/BzrVcsMessages").getString(
            "bzr4intellij.path_to_executable.text")));
    pathSelector = new TextFieldWithBrowseButton();
    pathSelector.setEnabled(true);
    panel1.add(pathSelector,
        new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL,
            GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW,
            GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, new Dimension(100, -1), null,
            null, 0, false));
    pathDefaultButton = new JButton();
    this.$$$loadButtonText$$$(pathDefaultButton,
        ResourceBundle.getBundle("org/emergent/bzr4j/intellij/BzrVcsMessages").getString(
            "configdialog.default_path_button.text"));
    panel1.add(pathDefaultButton,
        new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL,
            GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
            GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    final JLabel label1 = new JLabel();
    this.$$$loadLabelText$$$(label1,
        ResourceBundle.getBundle("org/emergent/bzr4j/intellij/BzrVcsMessages").getString("configpanel.exe_path.text"));
    panel1.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
        GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    final Spacer spacer1 = new Spacer();
    basePanel.add(spacer1,
        new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1,
            GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    final JPanel panel2 = new JPanel();
    panel2.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
    basePanel.add(panel2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH,
        GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
        GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
    panel2.setBorder(BorderFactory.createTitledBorder(
        ResourceBundle.getBundle("org/emergent/bzr4j/intellij/BzrVcsMessages").getString(
            "configpanel.miscellaneous_group.text")));
    m_trimAnnotationCheckBox = new JCheckBox();
    this.$$$loadButtonText$$$(m_trimAnnotationCheckBox,
        ResourceBundle.getBundle("org/emergent/bzr4j/intellij/BzrVcsMessages").getString(
            "configpanel.trim_annotation_author.text"));
    panel2.add(m_trimAnnotationCheckBox,
        new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
            GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
            GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    final Spacer spacer2 = new Spacer();
    panel2.add(spacer2, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL,
        GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
  }

  /** @noinspection ALL */
  private void $$$loadLabelText$$$(JLabel component, String text) {
    StringBuffer result = new StringBuffer();
    boolean haveMnemonic = false;
    char mnemonic = '\0';
    int mnemonicIndex = -1;
    for (int i = 0; i < text.length(); i++) {
      if (text.charAt(i) == '&') {
        i++;
        if (i == text.length()) break;
        if (!haveMnemonic && text.charAt(i) != '&') {
          haveMnemonic = true;
          mnemonic = text.charAt(i);
          mnemonicIndex = result.length();
        }
      }
      result.append(text.charAt(i));
    }
    component.setText(result.toString());
    if (haveMnemonic) {
      component.setDisplayedMnemonic(mnemonic);
      component.setDisplayedMnemonicIndex(mnemonicIndex);
    }
  }

  /** @noinspection ALL */
  private void $$$loadButtonText$$$(AbstractButton component, String text) {
    StringBuffer result = new StringBuffer();
    boolean haveMnemonic = false;
    char mnemonic = '\0';
    int mnemonicIndex = -1;
    for (int i = 0; i < text.length(); i++) {
      if (text.charAt(i) == '&') {
        i++;
        if (i == text.length()) break;
        if (!haveMnemonic && text.charAt(i) != '&') {
          haveMnemonic = true;
          mnemonic = text.charAt(i);
          mnemonicIndex = result.length();
        }
      }
      result.append(text.charAt(i));
    }
    component.setText(result.toString());
    if (haveMnemonic) {
      component.setMnemonic(mnemonic);
      component.setDisplayedMnemonicIndex(mnemonicIndex);
    }
  }

  /** @noinspection ALL */
  public JComponent $$$getRootComponent$$$() {
    return basePanel;
  }
}
